import {
  Product,
  Warehouse,
  Receipt,
  DeliveryOrder,
  InternalTransfer,
  StockAdjustment,
  StockLedgerEntry,
  ReorderingRule,
  InventoryCategory,
  User,
} from '@/types/inventory';

export const INITIAL_USER: User = {
  id: 'usr-01',
  name: 'Alex Vance',
  email: 'alex.vance@stocksense.logistics',
  role: 'inventory_manager',
  department: 'Central Logistics & Supply Operations',
  warehouseId: 'all',
  assignedWarehouseName: 'All Warehouses',
  avatar: 'AV',
};

export const SECONDARY_USER: User = {
  id: 'usr-02',
  name: 'Marcus Miller',
  email: 'marcus.m@stocksense.logistics',
  role: 'warehouse_staff',
  department: 'Floor Execution & Fulfillment',
  warehouseId: 'wh-main',
  assignedWarehouseName: 'Main Central Hub',
  avatar: 'MM',
};

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-main',
    name: 'Main Central Hub',
    code: 'WH-MAIN',
    address: 'Terminal 4, North Logistics Corridor',
    isMain: true,
    locations: [
      { id: 'loc-main-rec', name: 'Receiving Dock A', code: 'REC-A', warehouseId: 'wh-main', type: 'receiving', capacity: 1500 },
      { id: 'loc-main-ra', name: 'Heavy Rack A (Raw)', code: 'RACK-A', warehouseId: 'wh-main', type: 'rack', capacity: 8000 },
      { id: 'loc-main-rb', name: 'Standard Rack B (Components)', code: 'RACK-B', warehouseId: 'wh-main', type: 'rack', capacity: 6000 },
      { id: 'loc-main-stg', name: 'Outbound Staging Bay', code: 'STG-01', warehouseId: 'wh-main', type: 'staging', capacity: 2000 },
    ],
  },
  {
    id: 'wh-prod',
    name: 'Production Facility Warehouse',
    code: 'WH-PROD',
    address: 'Building 12, Advanced Manufacturing Zone',
    isMain: false,
    locations: [
      { id: 'loc-prod-flr', name: 'Assembly Floor Area', code: 'FLR-01', warehouseId: 'wh-prod', type: 'floor', capacity: 4000 },
      { id: 'loc-prod-rc', name: 'Production Rack C', code: 'RACK-C', warehouseId: 'wh-prod', type: 'rack', capacity: 3500 },
      { id: 'loc-prod-shp', name: 'Finished Goods Bay', code: 'SHP-01', warehouseId: 'wh-prod', type: 'shipping', capacity: 2500 },
    ],
  },
  {
    id: 'wh-sec',
    name: 'East Buffer Warehouse',
    code: 'WH-EAST',
    address: 'Pier 9, Logistics Harbor',
    isMain: false,
    locations: [
      { id: 'loc-east-stk', name: 'Bulk Overflow Storage', code: 'BLK-01', warehouseId: 'wh-sec', type: 'rack', capacity: 12000 },
      { id: 'loc-east-rec', name: 'Intake Bay E', code: 'REC-E', warehouseId: 'wh-sec', type: 'receiving', capacity: 3000 },
    ],
  },
];

export const INITIAL_CATEGORIES: InventoryCategory[] = [
  { id: 'cat-raw', name: 'Raw Materials', code: 'RAW', description: 'Metals, bars, rods, polymers, unprocessed stock', productCount: 2 },
  { id: 'cat-fast', name: 'Fasteners & Hardware', code: 'FST', description: 'Bolts, nuts, rivets, washers, brackets', productCount: 1 },
  { id: 'cat-mech', name: 'Mechanical Assemblies', code: 'MCH', description: 'Valves, actuators, couplings, pumps', productCount: 1 },
  { id: 'cat-elec', name: 'Electrical & Cables', code: 'ELC', description: 'Wiring, spools, connectors, relays', productCount: 1 },
  { id: 'cat-fin', name: 'Finished Goods', code: 'FGD', description: 'Packaged commercial goods ready for dispatch', productCount: 1 },
  { id: 'cat-eqp', name: 'Storage & Tooling', code: 'TLS', description: 'Pallet racking, handling systems, tools', productCount: 1 },
  { id: 'cat-rob', name: 'Automation & Robotics', code: 'ROB', description: 'Servo motors, drivers, optical sensors', productCount: 1 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Steel Rods (Grade 40 Industrial)',
    sku: 'STL-001',
    barcode: '890100452011',
    category: 'Raw Materials',
    unitOfMeasure: 'kg',
    costPrice: 4.25,
    sellingPrice: 7.80,
    reorderPoint: 50,
    maxStock: 300,
    description: 'High-tensile carbon steel rods for machining and structural framing.',
    supplierName: 'MetalWorks Ltd.',
    locationStock: [
      { locationId: 'loc-main-ra', locationName: 'Heavy Rack A (Raw)', warehouseId: 'wh-main', warehouseName: 'Main Central Hub', quantity: 42, reserved: 0 },
      { locationId: 'loc-prod-rc', locationName: 'Production Rack C', warehouseId: 'wh-prod', warehouseName: 'Production Facility Warehouse', quantity: 80, reserved: 10 },
    ],
    createdAt: '2026-08-10T08:00:00Z',
    updatedAt: '2026-09-26T09:42:00Z',
  },
  {
    id: 'prod-02',
    name: 'Industrial Bolts M8 × 40mm',
    sku: 'BLT-M8',
    barcode: '890100452012',
    category: 'Fasteners & Hardware',
    unitOfMeasure: 'units',
    costPrice: 0.35,
    sellingPrice: 0.95,
    reorderPoint: 500,
    maxStock: 2500,
    description: 'Grade 8.8 zinc-plated structural hex head bolts.',
    supplierName: 'Titan Fasteners Corp',
    locationStock: [
      { locationId: 'loc-main-rb', locationName: 'Standard Rack B (Components)', warehouseId: 'wh-main', warehouseName: 'Main Central Hub', quantity: 0, reserved: 0 },
    ],
    createdAt: '2026-08-12T09:30:00Z',
    updatedAt: '2026-09-25T14:10:00Z',
  },
  {
    id: 'prod-03',
    name: 'Aluminum Sheets 4mm Precision',
    sku: 'ALM-4MM',
    barcode: '890100452013',
    category: 'Raw Materials',
    unitOfMeasure: 'units',
    costPrice: 48.00,
    sellingPrice: 75.00,
    reorderPoint: 40,
    maxStock: 200,
    description: '6061-T6 aviation grade aluminum alloy plate sheets (1200x2400mm).',
    supplierName: 'AlloyTech Global',
    locationStock: [
      { locationId: 'loc-main-ra', locationName: 'Heavy Rack A (Raw)', warehouseId: 'wh-main', warehouseName: 'Main Central Hub', quantity: 135, reserved: 15 },
      { locationId: 'loc-east-stk', locationName: 'Bulk Overflow Storage', warehouseId: 'wh-sec', warehouseName: 'East Buffer Warehouse', quantity: 60, reserved: 0 },
    ],
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-09-24T16:20:00Z',
  },
  {
    id: 'prod-04',
    name: 'Ergonomic Executive Task Chairs',
    sku: 'CHR-ERG',
    barcode: '890100452014',
    category: 'Finished Goods',
    unitOfMeasure: 'units',
    costPrice: 85.00,
    sellingPrice: 195.00,
    reorderPoint: 15,
    maxStock: 100,
    description: 'Fully adjustable mesh back task chairs with lumbar reinforcement.',
    supplierName: 'Apex Seating Systems',
    locationStock: [
      { locationId: 'loc-prod-shp', locationName: 'Finished Goods Bay', warehouseId: 'wh-prod', warehouseName: 'Production Facility Warehouse', quantity: 28, reserved: 20 },
      { locationId: 'loc-main-stg', locationName: 'Outbound Staging Bay', warehouseId: 'wh-main', warehouseName: 'Main Central Hub', quantity: 14, reserved: 0 },
    ],
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-26T13:20:00Z',
  },
  {
    id: 'prod-05',
    name: 'Hydraulic High-Pressure Valve Assembly',
    sku: 'HYD-VLV',
    barcode: '890100452015',
    category: 'Mechanical Assemblies',
    unitOfMeasure: 'units',
    costPrice: 140.00,
    sellingPrice: 280.00,
    reorderPoint: 20,
    maxStock: 80,
    description: 'Heavy duty directional flow hydraulic valve rated to 350 bar.',
    supplierName: 'Vanguard Fluid Power',
    locationStock: [
      { locationId: 'loc-main-rb', locationName: 'Standard Rack B (Components)', warehouseId: 'wh-main', warehouseName: 'Main Central Hub', quantity: 54, reserved: 4 },
    ],
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-09-23T11:15:00Z',
  },
  {
    id: 'prod-06',
    name: 'Copper Wire Spools 50m Heavy Gauge',
    sku: 'CPR-W50',
    barcode: '890100452016',
    category: 'Electrical & Cables',
    unitOfMeasure: 'units',
    costPrice: 26.50,
    sellingPrice: 49.00,
    reorderPoint: 30,
    maxStock: 150,
    description: 'Insulated copper conductor spool 2.5mm² double coated for industrial conduits.',
    supplierName: 'ElectroConduit Supply',
    locationStock: [
      { locationId: 'loc-main-rb', locationName: 'Standard Rack B (Components)', warehouseId: 'wh-main', warehouseName: 'Main Central Hub', quantity: 18, reserved: 0 },
    ],
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-26T10:00:00Z',
  },
  {
    id: 'prod-07',
    name: 'Heavy Duty Structural Pallet Racks',
    sku: 'PLT-RCK',
    barcode: '890100452017',
    category: 'Storage & Tooling',
    unitOfMeasure: 'units',
    costPrice: 320.00,
    sellingPrice: 560.00,
    reorderPoint: 5,
    maxStock: 30,
    description: 'Modular beam upright system 3.6m uprights with heavy crossbeams.',
    supplierName: 'StorMax Logistics',
    locationStock: [
      { locationId: 'loc-east-stk', locationName: 'Bulk Overflow Storage', warehouseId: 'wh-sec', warehouseName: 'East Buffer Warehouse', quantity: 14, reserved: 0 },
    ],
    createdAt: '2026-09-05T08:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
  },
  {
    id: 'prod-08',
    name: 'Precision Servo Motor 750W AC',
    sku: 'MOT-SRV',
    barcode: '890100452018',
    category: 'Automation & Robotics',
    unitOfMeasure: 'units',
    costPrice: 210.00,
    sellingPrice: 410.00,
    reorderPoint: 10,
    maxStock: 50,
    description: 'Brushless closed-loop servo with 17-bit magnetic absolute encoder.',
    supplierName: 'OmniDrive Robotics',
    locationStock: [
      { locationId: 'loc-prod-rc', locationName: 'Production Rack C', warehouseId: 'wh-prod', warehouseName: 'Production Facility Warehouse', quantity: 32, reserved: 5 },
    ],
    createdAt: '2026-09-10T15:30:00Z',
    updatedAt: '2026-09-25T17:45:00Z',
  },
];

export const INITIAL_RECEIPTS: Receipt[] = [
  {
    id: 'rec-1042',
    receiptNumber: 'REC-1042',
    supplierName: 'MetalWorks Ltd.',
    destinationWarehouseId: 'wh-main',
    destinationLocationId: 'loc-main-rec',
    destinationLocationName: 'Main Central Hub → Receiving Dock A',
    status: 'ready',
    items: [
      {
        productId: 'prod-01',
        productName: 'Steel Rods (Grade 40 Industrial)',
        sku: 'STL-001',
        quantityExpected: 100,
        quantityReceived: 100,
        unitOfMeasure: 'kg',
        unitCost: 4.25,
      },
    ],
    notes: 'Urgent replenish for structural framing line. Inbound bill #BL-8921.',
    createdAt: '2026-09-26T08:30:00Z',
    createdByName: 'Alex Vance',
  },
  {
    id: 'rec-1041',
    receiptNumber: 'REC-1041',
    supplierName: 'Titan Fasteners Corp',
    destinationWarehouseId: 'wh-main',
    destinationLocationId: 'loc-main-rec',
    destinationLocationName: 'Main Central Hub → Receiving Dock A',
    status: 'waiting',
    items: [
      {
        productId: 'prod-02',
        productName: 'Industrial Bolts M8 × 40mm',
        sku: 'BLT-M8',
        quantityExpected: 1500,
        quantityReceived: 0,
        unitOfMeasure: 'units',
        unitCost: 0.35,
      },
    ],
    notes: 'Carrier scheduled arrival 14:00 today. Critical out-of-stock replacement.',
    createdAt: '2026-09-26T07:15:00Z',
    createdByName: 'Alex Vance',
  },
  {
    id: 'rec-1040',
    receiptNumber: 'REC-1040',
    supplierName: 'ElectroConduit Supply',
    destinationWarehouseId: 'wh-main',
    destinationLocationId: 'loc-main-rec',
    destinationLocationName: 'Main Central Hub → Receiving Dock A',
    status: 'draft',
    items: [
      {
        productId: 'prod-06',
        productName: 'Copper Wire Spools 50m Heavy Gauge',
        sku: 'CPR-W50',
        quantityExpected: 60,
        quantityReceived: 0,
        unitOfMeasure: 'units',
        unitCost: 26.50,
      },
    ],
    notes: 'Draft order awaiting PO sign-off from finance.',
    createdAt: '2026-09-25T16:00:00Z',
    createdByName: 'Marcus Miller',
  },
  {
    id: 'rec-1039',
    receiptNumber: 'REC-1039',
    supplierName: 'AlloyTech Global',
    destinationWarehouseId: 'wh-main',
    destinationLocationId: 'loc-main-ra',
    destinationLocationName: 'Main Central Hub → Heavy Rack A (Raw)',
    status: 'done',
    items: [
      {
        productId: 'prod-03',
        productName: 'Aluminum Sheets 4mm Precision',
        sku: 'ALM-4MM',
        quantityExpected: 50,
        quantityReceived: 50,
        unitOfMeasure: 'units',
        unitCost: 48.00,
      },
    ],
    notes: 'Shipment cleared QA inspection. Sheet thickness verified.',
    createdAt: '2026-09-24T10:00:00Z',
    validatedAt: '2026-09-24T14:22:00Z',
    createdByName: 'Alex Vance',
  },
];

export const INITIAL_DELIVERIES: DeliveryOrder[] = [
  {
    id: 'del-1048',
    deliveryNumber: 'DEL-1048',
    customerName: 'AeroStructures Engineering',
    sourceWarehouseId: 'wh-main',
    sourceLocationId: 'loc-main-ra',
    sourceLocationName: 'Main Central Hub → Heavy Rack A (Raw)',
    stage: 'pack',
    status: 'ready',
    trackingNumber: 'TRK-9832140',
    items: [
      {
        productId: 'prod-01',
        productName: 'Steel Rods (Grade 40 Industrial)',
        sku: 'STL-001',
        quantityRequested: 20,
        quantityPicked: 20,
        quantityPacked: 20,
        unitOfMeasure: 'kg',
      },
    ],
    notes: 'Priority dispatch. High-speed courier collection requested.',
    createdAt: '2026-09-26T08:15:00Z',
    createdByName: 'Marcus Miller',
  },
  {
    id: 'del-1049',
    deliveryNumber: 'DEL-1049',
    customerName: 'Metropolitan Commercial Spaces',
    sourceWarehouseId: 'wh-prod',
    sourceLocationId: 'loc-prod-shp',
    sourceLocationName: 'Production Facility Warehouse → Finished Goods Bay',
    stage: 'pick',
    status: 'waiting',
    trackingNumber: 'TRK-9832141',
    items: [
      {
        productId: 'prod-04',
        productName: 'Ergonomic Executive Task Chairs',
        sku: 'CHR-ERG',
        quantityRequested: 20,
        quantityPicked: 10,
        quantityPacked: 0,
        unitOfMeasure: 'units',
      },
    ],
    notes: 'Sales order #SO-4401 for 20 chairs.',
    createdAt: '2026-09-26T09:00:00Z',
    createdByName: 'Alex Vance',
  },
  {
    id: 'del-1047',
    deliveryNumber: 'DEL-1047',
    customerName: 'RoboWorks Systems Inc.',
    sourceWarehouseId: 'wh-prod',
    sourceLocationId: 'loc-prod-rc',
    sourceLocationName: 'Production Facility Warehouse → Production Rack C',
    stage: 'done',
    status: 'done',
    trackingNumber: 'TRK-9832139',
    items: [
      {
        productId: 'prod-08',
        productName: 'Precision Servo Motor 750W AC',
        sku: 'MOT-SRV',
        quantityRequested: 8,
        quantityPicked: 8,
        quantityPacked: 8,
        unitOfMeasure: 'units',
      },
    ],
    notes: 'Completed batch release to customer staging.',
    createdAt: '2026-09-25T11:20:00Z',
    validatedAt: '2026-09-25T15:40:00Z',
    createdByName: 'Alex Vance',
  },
];

export const INITIAL_TRANSFERS: InternalTransfer[] = [
  {
    id: 'trf-201',
    transferNumber: 'TRF-0201',
    sourceWarehouseId: 'wh-main',
    sourceLocationId: 'loc-main-ra',
    sourceLocationName: 'Main Central Hub [Heavy Rack A]',
    destinationWarehouseId: 'wh-prod',
    destinationLocationId: 'loc-prod-rc',
    destinationLocationName: 'Production Facility [Production Rack C]',
    status: 'ready',
    scheduledDate: '2026-09-26T10:15:00Z',
    createdByName: 'Alex Vance',
    items: [
      {
        productId: 'prod-01',
        productName: 'Steel Rods (Grade 40 Industrial)',
        sku: 'STL-001',
        quantity: 120,
        unitOfMeasure: 'kg',
      },
    ],
    notes: 'Routine replenishment from bulk raw store to fabrication line.',
  },
  {
    id: 'trf-202',
    transferNumber: 'TRF-0202',
    sourceWarehouseId: 'wh-sec',
    sourceLocationId: 'loc-east-stk',
    sourceLocationName: 'East Buffer Warehouse [Bulk Overflow]',
    destinationWarehouseId: 'wh-main',
    destinationLocationId: 'loc-main-ra',
    destinationLocationName: 'Main Central Hub [Heavy Rack A]',
    status: 'waiting',
    scheduledDate: '2026-09-26T15:00:00Z',
    createdByName: 'Marcus Miller',
    items: [
      {
        productId: 'prod-03',
        productName: 'Aluminum Sheets 4mm Precision',
        sku: 'ALM-4MM',
        quantity: 30,
        unitOfMeasure: 'units',
      },
    ],
    notes: 'Buffer transfer via inter-facility shuttle truck #04.',
  },
  {
    id: 'trf-200',
    transferNumber: 'TRF-0200',
    sourceWarehouseId: 'wh-main',
    sourceLocationId: 'loc-main-stg',
    sourceLocationName: 'Main Central Hub [Outbound Staging]',
    destinationWarehouseId: 'wh-prod',
    destinationLocationId: 'loc-prod-shp',
    destinationLocationName: 'Production Facility [Finished Goods Bay]',
    status: 'done',
    scheduledDate: '2026-09-25T14:00:00Z',
    completedAt: '2026-09-25T14:45:00Z',
    createdByName: 'Alex Vance',
    items: [
      {
        productId: 'prod-04',
        productName: 'Ergonomic Executive Task Chairs',
        sku: 'CHR-ERG',
        quantity: 14,
        unitOfMeasure: 'units',
      },
    ],
    notes: 'Consolidation of completed units for direct export palletizing.',
  },
];

export const INITIAL_ADJUSTMENTS: StockAdjustment[] = [
  {
    id: 'adj-01',
    adjustmentNumber: 'ADJ-2026-041',
    warehouseId: 'wh-main',
    warehouseName: 'Main Central Hub',
    reason: 'Damaged',
    status: 'done',
    notes: 'Forklift impact damaged bottom bundle of steel rods during unloading.',
    createdAt: '2026-09-26T09:10:00Z',
    createdByName: 'Marcus Miller',
    items: [
      {
        productId: 'prod-01',
        productName: 'Steel Rods (Grade 40 Industrial)',
        sku: 'STL-001',
        locationId: 'loc-main-ra',
        locationName: 'Heavy Rack A (Raw)',
        recordedQuantity: 45,
        physicalQuantity: 42,
        difference: -3,
        unitOfMeasure: 'kg',
      },
    ],
  },
  {
    id: 'adj-02',
    adjustmentNumber: 'ADJ-2026-040',
    warehouseId: 'wh-main',
    warehouseName: 'Main Central Hub',
    reason: 'Inventory Count / Cycle',
    status: 'done',
    notes: 'Weekly cycle audit in Standard Rack B. Found extra bag of fasteners.',
    createdAt: '2026-09-24T18:00:00Z',
    createdByName: 'Alex Vance',
    items: [
      {
        productId: 'prod-05',
        productName: 'Hydraulic High-Pressure Valve Assembly',
        sku: 'HYD-VLV',
        locationId: 'loc-main-rb',
        locationName: 'Standard Rack B (Components)',
        recordedQuantity: 52,
        physicalQuantity: 54,
        difference: +2,
        unitOfMeasure: 'units',
      },
    ],
  },
  {
    id: 'adj-03',
    adjustmentNumber: 'ADJ-2026-042',
    warehouseId: 'wh-main',
    warehouseName: 'Main Central Hub',
    reason: 'Inventory Count / Cycle',
    status: 'waiting',
    notes: 'Floor cycle count by Marcus Miller: Found 2 extra standard fasteners on standard rack B.',
    createdAt: '2026-09-26T10:30:00Z',
    createdByName: 'Marcus Miller',
    items: [
      {
        productId: 'prod-02',
        productName: 'Heavy Duty Hex Bolts (M12×60)',
        sku: 'BLT-HEX-12',
        locationId: 'loc-main-rb',
        locationName: 'Standard Rack B (Components)',
        recordedQuantity: 180,
        physicalQuantity: 182,
        difference: 2,
        unitOfMeasure: 'boxes',
      },
    ],
  },
];

export const INITIAL_LEDGER: StockLedgerEntry[] = [
  {
    id: 'led-101',
    timestamp: '2026-09-26T09:42:00Z',
    productId: 'prod-01',
    productName: 'Steel Rods (Grade 40 Industrial)',
    sku: 'STL-001',
    operationType: 'Receipt',
    referenceNumber: 'REC-1042',
    sourceLocationName: 'Vendor: MetalWorks Ltd.',
    destinationLocationName: 'Main Central Hub → Heavy Rack A',
    quantityDelta: 100,
    unitOfMeasure: 'kg',
    resultingTotalStock: 122,
    userName: 'Alex Vance',
    status: 'Completed',
    notes: 'Incoming raw steel verified and racked.',
  },
  {
    id: 'led-102',
    timestamp: '2026-09-26T10:15:00Z',
    productId: 'prod-01',
    productName: 'Steel Rods (Grade 40 Industrial)',
    sku: 'STL-001',
    operationType: 'Internal Transfer',
    referenceNumber: 'TRF-0201',
    sourceLocationName: 'Main Central Hub [Rack A]',
    destinationLocationName: 'Production Facility [Rack C]',
    quantityDelta: 0, // Transfer net company delta is 0
    unitOfMeasure: 'kg',
    resultingTotalStock: 122,
    userName: 'Alex Vance',
    status: 'Completed',
    notes: 'Moved 120 kg to fabrication line buffer.',
  },
  {
    id: 'led-103',
    timestamp: '2026-09-26T13:20:00Z',
    productId: 'prod-04',
    productName: 'Ergonomic Executive Task Chairs',
    sku: 'CHR-ERG',
    operationType: 'Delivery',
    referenceNumber: 'DEL-1049',
    sourceLocationName: 'Production Facility → Finished Goods',
    destinationLocationName: 'Customer: Metropolitan Spaces',
    quantityDelta: -20,
    unitOfMeasure: 'units',
    resultingTotalStock: 28,
    userName: 'Marcus Miller',
    status: 'Completed',
    notes: 'Dispatched via North Gate loading dock.',
  },
  {
    id: 'led-104',
    timestamp: '2026-09-26T09:10:00Z',
    productId: 'prod-01',
    productName: 'Steel Rods (Grade 40 Industrial)',
    sku: 'STL-001',
    operationType: 'Adjustment',
    referenceNumber: 'ADJ-2026-041',
    sourceLocationName: 'Main Central Hub [Rack A]',
    destinationLocationName: 'Scrap / Damaged Quarantine',
    quantityDelta: -3,
    unitOfMeasure: 'kg',
    resultingTotalStock: 122,
    userName: 'Marcus Miller',
    status: 'Completed',
    notes: 'Bent rod scrapped due to forklift drop.',
  },
  {
    id: 'led-105',
    timestamp: '2026-09-25T14:40:00Z',
    productId: 'prod-08',
    productName: 'Precision Servo Motor 750W AC',
    sku: 'MOT-SRV',
    operationType: 'Delivery',
    referenceNumber: 'DEL-1047',
    sourceLocationName: 'Production Facility [Rack C]',
    destinationLocationName: 'Customer: RoboWorks Systems',
    quantityDelta: -8,
    unitOfMeasure: 'units',
    resultingTotalStock: 32,
    userName: 'Alex Vance',
    status: 'Completed',
    notes: 'Released with calibration test certificate #CC-190.',
  },
];

export const INITIAL_REORDER_RULES: ReorderingRule[] = [
  {
    id: 'rule-01',
    productId: 'prod-01',
    productName: 'Steel Rods (Grade 40 Industrial)',
    sku: 'STL-001',
    warehouseId: 'wh-main',
    warehouseName: 'Main Central Hub',
    minStock: 50,
    maxStock: 300,
    reorderQuantity: 250,
    unitOfMeasure: 'kg',
    isActive: true,
    leadTimeDays: 4,
    supplierName: 'MetalWorks Ltd.',
    lastTriggeredAt: '2026-09-26T06:00:00Z',
  },
  {
    id: 'rule-02',
    productId: 'prod-02',
    productName: 'Industrial Bolts M8 × 40mm',
    sku: 'BLT-M8',
    warehouseId: 'wh-main',
    warehouseName: 'Main Central Hub',
    minStock: 500,
    maxStock: 2500,
    reorderQuantity: 2000,
    unitOfMeasure: 'units',
    isActive: true,
    leadTimeDays: 2,
    supplierName: 'Titan Fasteners Corp',
    lastTriggeredAt: '2026-09-25T14:10:00Z',
  },
  {
    id: 'rule-03',
    productId: 'prod-06',
    productName: 'Copper Wire Spools 50m Heavy Gauge',
    sku: 'CPR-W50',
    warehouseId: 'wh-main',
    warehouseName: 'Main Central Hub',
    minStock: 30,
    maxStock: 150,
    reorderQuantity: 120,
    unitOfMeasure: 'units',
    isActive: true,
    leadTimeDays: 5,
    supplierName: 'ElectroConduit Supply',
    lastTriggeredAt: '2026-09-26T10:00:00Z',
  },
  {
    id: 'rule-04',
    productId: 'prod-04',
    productName: 'Ergonomic Executive Task Chairs',
    sku: 'CHR-ERG',
    warehouseId: 'wh-prod',
    warehouseName: 'Production Facility Warehouse',
    minStock: 15,
    maxStock: 100,
    reorderQuantity: 75,
    unitOfMeasure: 'units',
    isActive: true,
    leadTimeDays: 7,
    supplierName: 'Apex Seating Systems',
  },
];
